### ISSUE TITLE
User

### ISSUE THREAD

**Issue by MovsisyanM** [MovsisyanM/DB-Queues#1]
Properties:  
- id
- first_name
- last_name
- email
- num_tickets
- password
- joined_since

**Comment by xxorenn** [comment]
id SERIAL PRIMARY KEY,
first_name VARCHAR(100) NOT NULL,
last_name VARCHAR(100) NOT NULL,
email VARCHAR(100) NOT NULL,
joined_since TIMESTAMP DEFAULT NOW()
