### ISSUE TITLE
Come up with view ideas

### ISSUE THREAD

**Issue by MovsisyanM** [MovsisyanM/DB-Queues#11]

**Comment by MovsisyanM** [comment]
- Total number of tickets served
- Top n companies in terms of tickets served
- Average wait time of branch
- Top n employees in terms of tickets served (per company)
- Number of branches a company has

**Comment by MovsisyanM** [comment]
- Number of employees vs branch given company
- Number of employees vs company
- Number of tickets served in a year
- Number of tickets served in a month
- Number of tickets served in a week
- Number of tickets served in a day
- Number of tickets served in a year (cyclical)
- Number of tickets served in a month (cyclical)
- Number of tickets served in a week (cyclical)
- Number of tickets served in a day (cyclical)
- Proportion of users using each language
- New users per week/month/year
- New employees per month/year
- Binned number of average hours worked vs company (normalized per person)

**Comment by Armennon** [comment]
-Companies with average waiting time more than 10 minutes
-User's top 'favorite' companies to book ticket
-Average employee serving time
-average time of user being late
-number of missed tickets per user per month
-most loaded branches of company in terms of tickets served or avg waiting time
