### ISSUE TITLE
Employee

### ISSUE THREAD

**Issue by MovsisyanM** [MovsisyanM/DB-Queues#5]
Properties:  
- id
- first_name
- last_name
- email
- phone
- position

**Comment by xxorenn** [comment]
- id SERIAL PRIMARY KEY,
- first_name VARCHAR(50),
- last_name VARCHAR(50),
- email VARCHAR(100),
- phone VARCHAR(50),
- position VARCHAR(30),
- branch_id SERIAL references Branch (id)

**Comment by MovsisyanM** [comment]
removing branch_id property
